spring.application.name=demoapi
server.port=8080

spring.mongodb.username=${MONGO_USERNAME}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.host=${MONGO_HOST:localhost}
spring.mongodb.port=${MONGO_PORT:27017}
spring.mongodb.database=${MONGO_DATABASE:newdb}
spring.mongodb.authentication-database=${MONGO_AUTH_DATABASE:admin}

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
logging.level.root=INFO
logging.level.com.example.demoapi=INFO

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
