spring.application.name=demoapi
server.port=8080

spring.mongodb.username=${MONGO_USERNAME}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=newdb
spring.mongodb.authentication-database=admin

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
logging.level.root=INFO
logging.level.com.example.demoapi=INFO

app.jwt.secret=PmiNqml7zAJnVERCKWQwuSNJ7h/+44kT1OvfrGjTpMU=
app.jwt.expiration-ms=3600000

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n