spring.application.name=demoapi
server.port=8080

spring.mongodb.username=ja
spring.mongodb.password=57752369
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=newdb
spring.mongodb.authentication-database=admin

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
logging.level.com.example.demoapi=INFO

app.jwt.secret=PmiNqml7zAJnVERCKWQwuSNJ7h/+44kT1OvfrGjTpMU=
app.jwt.expiration-ms=3600000
